name: "Publish to NuGet Gallery"

on: 
  release:
    types: [published]

env:
  PROJECT_PATH: SimpleMimeMap.Core/SimpleMimeMap.Core.csproj
  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}/output
  NUGET_SOURCE_URL: "'https://api.nuget.org/v3/index.json'"

jobs:
  publish:
    name: "Publish to NuGet Gallery"
    runs-on: "windows-latest"
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        
      - name: "Install Dotnet"
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: "Pack project"
        run: dotnet pack ${{ env.PROJECT_PATH }} -p:PackageVersion=${{ github.event.release.name }} --configuration Release --include-symbols --output ${{ env.PACKAGE_OUTPUT_DIRECTORY }}

      - name:  "Push package"
        run: dotnet nuget push ${{ env.PACKAGE_OUTPUT_DIRECTORY }}/SimpleMimeMap.${{ github.event.release.name }}.nupkg -s ${{ env.NUGET_SOURCE_URL }} -k ${{ secrets.NUGET_AUTH_TOKEN }}
